export const STOCKS_SELECTION = "STOCKS_SELECTION";
export const STOCK_INFO = "STOCK_INFO";
export const EXCHANGE_SELECTION = "EXCHANGE_SELECTION";


export const INIT_ACTIVITY_STATE = [{
    type: EXCHANGE_SELECTION
}];
